# simulation parameters
N: 50
Ts: 0.1

# drone model constants
m: 2.4
L: 0.2
J: 1.0
c: 10.0
g: 9.81

# weight matrices
qx:       10.0
qy:       12.0
qvx:      4.0
qvy:      12.0
qtheta:   32.0
qdtheta:  400.0
qu:       1.0