# simulation parameters
N: 50
Ts: 0.1

# drone model constants
m: 2.4
L: 0.2
J: 1.0
c: 10.0
g: 9.81

# weight matrices
qx:       200.0
qy:       200.0
qvx:      160.0
qvy:      160.0
qtheta:   100.0
qdtheta:  60.0
qu:       1.0